config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'home#index'

  devise_for :users

  resources :chats, only: [:index, :show, :create] do
    resources :messages, only:[:create, :index]
  end

  resources :posts do
    resources :comments
  end

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  #if chat is destroyed all messages and subscriptions will also be  destroyed
  has_many :users, through: :subscriptions
  validates :identifier, presence: true, uniqueness: true,    case_sensitive: false
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :attachment, AvatarUploader
  belongs_to :user
  has_many :comments

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :attachment, AvatarUploader


  has_many :messages
  has_many :subscriptions
  has_many :chats, through: :subscriptions
  def existing_chats_users
    existing_chat_users = []
    self.chats.each do |chat|
    existing_chat_users.concat(chat.subscriptions.where.not(user_id: self.id).map {|subscription| subscription.user})
    end
    existing_chat_users.uniq
  end
  # include Gravtastic
  #   gravtastic
  # acts_as_messageable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # before_action :configure_permitted_parameters, if: :devise_controller?

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!
  # before_action :get_mailbox
  # before_action :get_conversation, except: [:index]

  require 'securerandom'

  def index
    chats = current_user.chats
    @existing_chats_users = Chat.joins(:users).includes(:users).where(users: { id: current_user.id })

  end
# current_user.existing_chats_users
  def create
    @other_user = User.find(params[:other_user])
    @chat = find_chat(@other_user) || Chat.new(identifier: SecureRandom.hex)
    unless @chat.persisted?
      @chat.save
      @chat.subscriptions.create(user_id: current_user.id)
      @chat.subscriptions.create(user_id: @other_user.id)
    end
    redirect_to chat_path(current_user, @chat, other_user: @other_user.id)
  end

  def show
    @other_user = User.find(params[:other_user])
    @chat = Chat.find_by(id: params[:id])
    @message = Message.new
  end

  private

  def find_chat(second_user)
    chats = current_user.chats
    chats.each do |chat|
      chat.subscriptions.each do |s|
        return chat if s.user_id == second_user.id
      end
    end
    nil
  end

  def require_login
    redirect_to new_session_path unless logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :bdy, :post_id, :name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @new_post = Post.new
    @posts  = Post.all.includes(:comments)
    # @posts = Post.left_outer_joins(:comments).distinct.includes(:comments)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
def create
    message = Message.new(message_params)
    message.user = current_user
if message.save
      #broadcasting out to messages channel including the chat_id so messages are broadcasted to specific chat only
      ActionCable.server.broadcast( "messages_#{message_params[:chat_id]}",
      #message and user hold the data we render on the page using javascript
      message: message.content,
      user: message.user.user_name
      )
    else
      redirect_to chats_path
    end
  end
private
    def message_params
      params.require(:message).permit(:content, :chat_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.all
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params) do |post|
      post.user = current_user
    end
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:attachment, :content, :user_id, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/chats/index.html.erb
<h1>Chat index</h1>

<ul>
  <% if @existing_chats_users %>
    <% @existing_chats_users.each do |other_user| %>
      <% if other_user != current_user %>
        <li>
          <%= link_to(chat_path(current_user, :other_user => other_user.id), method: :post) do %>
          <%= other_user.user_name %>
        <% end %>
      </li>
    <% end %>
  <% end %>
<% end %>
</ul>
All Users:
<ul>
<% User.all.each do |other_user| %>
  <% if other_user != current_user %>
    <li>
      <%= link_to(chat_path(current_user, :other_user => other_user.id)) do %>
      <%= other_user.user_name %>

    <% end %>
  </li>
<% end %>
<% end %>
</ul>

app/views/chats/show.html.erb
<div>
  <h5>Chat with <%= @other_user.user_name %></h5>
  <% if @chat.messages.any? %>
    <div id="messages">
      <%= render partial: 'messages/message', collection: @chat.messages.order(id: :asc)%>
    </div>
  <%else%>
    <div id="messages">
    </div>
  <%end%>
</div>
<%= render partial: 'messages/message_form', locals: {message: @message, chat: @chat}%>
</div>
<script>
  createMessageChannel();
  // app/assets/javascripts/channels/messages.js
  messageForm();
  // app/assets/javascripts/messages_form.js
</script>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user, id: :comment_user %>
  </div>

  <div class="field">
    <%= form.label :bdy %>
    <%= form.text_area :bdy, id: :comment_bdy %>
    <%= form.hidden_field :post_id %>
  </div>
<!-- 
  <div class="field">
    <%#= form.label :post_id %>
    <%#= form.number_field :post_id, id: :comment_post_id %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.bdy %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Bdy:</strong>
  <%= @comment.bdy %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<div class="post-form">
  <%= form_for @new_post do |f| %>
  <div class="form-group">
    <%= f.label 'Update status' %><br>
    <%= f.text_area :content, class: 'form-control', autofocus: true, placeholder: 'How are you?' %>
    <%= f.file_field :attachment, class: 'form-control' %>
  </div>
  <%= f.submit :post, class: 'btn btn-primary'%>
<% end %>
</div>

<div class="news-feed">
  <div class="post-wrapper">
    <% @posts.each do |post| %>
      <div class="posts">
        <%#= post.id %>
        <p>
        <img src="<%= post.attachment %>"/>
        </p>
        <%= post.content %>
      </div>
      <% post.comments.each do |comment| %>
        <div class="comments">
          <%#= comment.user_id %>
          <%= comment.bdy %>
          <%#= comment.post_id %>
        </div>
        <% end %>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BabyfaceNetwork</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <h1>BabyFace Network</h1>
      <nav class="navbar">
        <div class="container">

            <% if user_signed_in? %>
              <%= link_to 'Home', root_path %>
              <%= link_to 'Profile', root_path %>
              <%= link_to 'Create Playdate', root_path %>
              <%= link_to 'Chat', chats_path %>
              <%= link_to 'Edit Profile', edit_user_registration_path %>
              <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
            <% else %>
            <%= link_to 'Log In', new_user_session_path %>
            <% end %>

        </div>
      </nav>
    <%= yield %>
  </div>
  </body>
</html>

app/views/messages/_message.html.erb
<%=form_for message, remote: true,authenticity_token: true do |f|%>
  <%= f.text_area :content, data: {textarea: "message"}%>
<!-- this hidden field is for the MessagesController and Action Cable to keep track of what chat this message belongs to -->
<%= f.hidden_field :chat_id, value: chat.id %>
<%end%>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :attachment %>
    <%= form.text_field :attachment, id: :post_attachment %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :post_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Attachment</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.attachment %></td>
        <td><%= post.content %></td>
        <td><%= post.user %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>Attachment:</strong>
  <%= @post.attachment %>

</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
<h3>Comments</h3>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user_name %></strong>
    <br>
    <p><%= comment.body %></p>
    <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
<% end %>
<%= render partial: 'comments/form', locals: { comment: @comment } %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>